/**
 * Firebase Service Types
 * 
 * Type definitions for Firebase/Firestore integration.
 * These extend existing app types with Firebase-specific fields.
 */

// Note: Uncomment this import after installing Firebase
// import { Timestamp } from 'firebase/firestore';

/**
 * Firestore Timestamp type placeholder
 * Replace with actual Timestamp when Firebase is installed
 */
type Timestamp = {
  seconds: number;
  nanoseconds: number;
  toDate: () => Date;
};

/**
 * Convert Date to Firestore Timestamp and vice versa
 */
export type FirestoreDate = Date | Timestamp;

/**
 * Base document interface with common Firestore fields
 */
export interface FirestoreDocument {
  id: string;
  createdAt: FirestoreDate;
  updatedAt?: FirestoreDate;
}

/**
 * User document in Firestore
 */
export interface FirestoreUser extends FirestoreDocument {
  email: string;
  phone?: string;
  displayName: string;
  role: 'staff' | 'hod' | 'admin';
  department?: string;
  institution?: string;
  place?: string;
  avatar?: string;
  avatarPosition?: { x: number; y: number };
  avatarZoom?: number;
  useDefaultAvatar?: boolean;
  dashboardColor?: string;
  customGradientStart?: string;
  customGradientEnd?: string;
  status?: 'active' | 'blocked';
}

/**
 * Question document in Firestore
 */
export interface FirestoreQuestion extends FirestoreDocument {
  content: string;
  answer: string;
  type: string;
  difficulty: 'easy' | 'medium' | 'hard';
  bloomsLevel: string;
  marks: number;
  topic: string;
  source: 'upload' | 'ai-assistant';
  /** 'gemini' = generated by Gemini AI, 'local' = template-based; optional for backward compatibility */
  generatedBy?: 'gemini' | 'local';
  materialId?: string;
  status: 'draft' | 'pending' | 'approved' | 'rejected';
  feedback?: string;
  options?: string[];
  correctOption?: number;
  examType?: string;
  department?: string;
  institution?: string;
  place?: string;
  staffId?: string;
  /** Display name snapshot for dashboards (avoids extra joins) */
  staffName?: string;
  isLocked?: boolean;
  lockedAt?: FirestoreDate;
  lockedBy?: string;
  hasUnlockRequest?: boolean;
  unlockRequestReason?: string;
  unlockedAt?: FirestoreDate;
  unlockedBy?: string;
  printedAt?: FirestoreDate;
}

/**
 * Material document in Firestore
 * Stored under users/{userId}/materials/{materialId}.
 * Original file in Cloud Storage at users/{userId}/materials/{materialId}/{fileName}.
 * Full extracted text in `content` (capped to stay under 1 MiB doc limit).
 */
export interface FirestoreMaterial extends FirestoreDocument {
  fileName: string;
  fileSize: number;
  fileType: string;
  totalPages: number;
  storageUrl: string; // Cloud Storage download URL for the original file
  title: string;
  subject: string;
  department: string;
  semester?: string;
  regulation?: string;
  staffId: string;
  institution?: string;
  place?: string;
  status: 'processing' | 'ready' | 'failed';
  // Full extracted text (capped ~900k chars for Firestore 1 MiB limit)
  content?: string;
  contentTruncated?: boolean;
  // NLP global results
  globalKeywords: string[];
  globalKeyPhrases: string[];
  academicLevel: string;
  chunkCount: number;
  vocabularyRichness: number;
  wordCount: number;
  extractionMethod?: string;
  processingTimeMs?: number;
  processedAt?: FirestoreDate;
  /** Topic names for list view (also stored in topics subcollection) */
  topicNames?: string[];
  /** Identifies extraction type: "quick" (text-only, fast) or "full" (tables, images/diagrams/OCR) */
  extractionType?: 'quick' | 'full';
}

/**
 * Material Chunk document in Firestore
 * Subcollection: materials/{materialId}/chunks/{chunkId}
 */
export interface FirestoreMaterialChunk {
  id: string; // materialId_chunkId (deterministic)
  materialId: string;
  staffId: string;
  chunkId: number;
  chunkType: string; // unit, topic, paragraph, section
  title: string;
  unit?: string;
  topic?: string;
  text: string;
  sentences: string[];
  keywords: string[];
  keyPhrases: string[];
  estimatedDifficulty: 'easy' | 'medium' | 'hard';
  wordCount: number;
  sentenceCount: number;
  hasDefinitions: boolean;
  hasFormulas: boolean;
  hasExamples: boolean;
  namedEntities: string[];
  createdAt: FirestoreDate;
}

/**
 * Material Topic document in Firestore
 * Subcollection: materials/{materialId}/topics/{topicId}
 */
export interface FirestoreMaterialTopic {
  id: string; // materialId_topicName (deterministic)
  materialId: string;
  staffId: string;
  name: string;
  relevance: number;
  subtopics: string[];
  keywords: string[];
  chunkIds: number[];
}

/**
 * Question Paper document in Firestore
 */
export interface FirestorePaper extends FirestoreDocument {
  title: string;
  examType: string;
  collegeName: string;
  departmentName: string;
  courseName: string;
  courseCode: string;
  semester: string;
  duration: string;
  maxMarks: number;
  date?: string;
  instructions: string[];
  courseOutcomes: { code: string; description: string }[];
  coMapping: { [key: string]: string };
  sections: {
    id: string;
    name: string;
    instructions?: string;
    questions: {
      id: string;
      questionNo: number;
      subDivision: string;
      content: string;
      marks: number;
      btl: string;
      type: string;
      answer?: string;
      alternativeId?: string;
      isAlternative?: boolean;
    }[];
  }[];
  paperColor: string;
  textColor: string;
  status: 'draft' | 'pending' | 'approved' | 'rejected' | 'print-ready' | 'submitted';
  feedback?: string;
  staffId?: string;
  staffName?: string;
  department?: string;
  institution?: string;
  place?: string;
  submittedAt?: FirestoreDate;
  /** Download URL of the PDF saved when submitted to HOD */
  pdfUrl?: string;
  isLocked?: boolean;
  lockedAt?: FirestoreDate;
  lockedBy?: string;
  hasUnlockRequest?: boolean;
  unlockRequestReason?: string;
  unlockedAt?: FirestoreDate;
  unlockedBy?: string;
  printedAt?: FirestoreDate;
  /** When true, staff has deleted this from their list; document stays for HOD. */
  deletedByStaff?: boolean;
}

/**
 * Notification document in Firestore
 */
export interface FirestoreNotification extends FirestoreDocument {
  type: 'approval' | 'rejection' | 'feedback' | 'info' | 'request' | 'reply' | 'print-ready';
  title: string;
  message: string;
  questionId?: string;
  paperId?: string;
  fromRole: 'staff' | 'hod' | 'admin';
  toRole: 'staff' | 'hod' | 'admin';
  fromUserId?: string;
  toUserId?: string;
  isRead: boolean;
  /** Soft-delete: recipient hid this; only admin can hard-delete */
  deletedByRecipient?: boolean;
  replyTo?: string;
  department?: string;
  institution?: string;
  place?: string;
}

/**
 * Chat Session document in Firestore
 */
export interface FirestoreChatSession extends FirestoreDocument {
  userId: string;
  staffName: string;
  title: string;
  /** Material linked to this session */
  materialId?: string;
  materialTitle?: string;
  materialSubject?: string;
  /** Department/institution context for security filtering */
  department?: string;
  institution?: string;
  place?: string;
  /** Session-level question config used during generation */
  questionConfig?: FirestoreChatQuestionConfig;
  /** Summary stats for quick retrieval */
  totalMessages: number;
  totalQuestionsGenerated: number;
  totalQuestionsSaved: number;
  /** Last activity for sorting */
  lastMessageAt?: FirestoreDate;
  status: 'active' | 'archived';
}

/**
 * Question configuration snapshot stored per session/message
 */
export interface FirestoreChatQuestionConfig {
  examType?: string;
  questionType?: string;
  difficulty?: string;
  bloomsLevel?: string;
  marks?: number;
  topic?: string;
  unit?: string;
  count?: number;
  isTwisted?: boolean;
  customInstructions?: string;
}

/**
 * Generated question with edit tracking
 */
export interface FirestoreChatGeneratedQuestion {
  id: string;
  content: string;
  answer: string;
  explanation?: string;
  type: string;
  difficulty: string;
  bloomsLevel?: string;
  topic: string;
  unit?: string;
  marks?: number;
  options?: string[];
  correctOption?: number;
  isTwisted?: boolean;
  /** Track edits made by staff after generation */
  originalContent?: string;
  originalAnswer?: string;
  wasEdited: boolean;
  editedAt?: FirestoreDate;
  /** Save status */
  savedToMyQuestions: boolean;
  savedToQuestionBank: boolean;
  savedAt?: FirestoreDate;
}

/**
 * Chat Message document in Firestore
 * Subcollection: chat_sessions/{sessionId}/messages/{messageId}
 */
export interface FirestoreChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: FirestoreDate;
  /** Staff's original prompt text */
  staffPrompt?: string;
  /** Question config active at time of this message */
  questionConfig?: FirestoreChatQuestionConfig;
  /** Material reference for RAG context */
  materialId?: string;
  materialChunksUsed?: string[];
  /** Questions generated in this message */
  generatedQuestions?: FirestoreChatGeneratedQuestion[];
  /** AI follow-up suggestions */
  suggestions?: string[];
  /** Intent detected from staff prompt */
  detectedIntent?: string;
  /** Processing metadata */
  processingTimeMs?: number;
  tokenCount?: number;
}

/**
 * Public chat share document in Firestore
 * Collection: chat_shares/{shareId}
 */
export interface FirestoreChatShare extends FirestoreDocument {
  /** Owner (creator) of share */
  userId: string;
  /** Source chat session */
  sessionId: string;
  /** Optional title for share page */
  title: string;
  /** Material info for context (display only) */
  materialId?: string;
  materialTitle?: string;
  /** Export payloads */
  text: string;
  html: string;
  /** Controls public access */
  isPublic: boolean;
}

/**
 * Security History Entry in Firestore
 */
export interface FirestoreSecurityHistory extends FirestoreDocument {
  action: 'locked' | 'unlocked' | 'unlock_requested' | 'unlock_approved' | 'unlock_denied' | 'relocked';
  itemType: 'question' | 'paper';
  itemId: string;
  itemTitle: string;
  performedBy: string;
  performedByRole: 'staff' | 'hod' | 'admin';
  reason?: string;
  department?: string;
  institution?: string;
  place?: string;
  timestamp: FirestoreDate;
}

/**
 * Question Bank Item in Firestore
 */
export interface FirestoreQuestionBankItem extends FirestoreDocument {
  content: string;
  answer?: string;
  marks: number;
  btl: string;
  type: string;
  topic: string;
  difficulty: string;
  examType: string;
  subject?: string;
  tags: string[];
  userId: string;
}

/**
 * Generated Question document in Firestore
 * Collection: generated_questions
 * Stores AI/config-generated questions with full provenance
 */
export interface FirestoreGeneratedQuestion extends FirestoreDocument {
  content: string;
  answer: string;
  explanation?: string;
  type: string; // mcq, short, long, descriptive
  difficulty: 'easy' | 'medium' | 'hard';
  bloomsLevel: string;
  marks: number;
  topic: string;
  unit?: string;
  subject?: string;
  source: 'upload' | 'ai-assistant';
  generationSource: 'config' | 'ai-chat'; // how was it generated
  materialId?: string;
  staffId: string;
  department?: string;
  institution?: string;
  place?: string;
  status: 'draft' | 'pending' | 'approved' | 'rejected';
  feedback?: string; // HOD feedback
  options?: string[];
  correctOption?: number;
  examType?: string;
  // Lock system
  isLocked?: boolean;
  lockedAt?: FirestoreDate;
  lockedBy?: string;
  hasUnlockRequest?: boolean;
  unlockRequestReason?: string;
  unlockedAt?: FirestoreDate;
  unlockedBy?: string;
  printedAt?: FirestoreDate;
}

/**
 * Feedback document in Firestore
 */
export interface FirestoreFeedback extends FirestoreDocument {
  rating: number;
  comment: string;
  userType: 'staff' | 'hod' | 'admin' | 'public';
  instituteName?: string;
  userEmail?: string;
  userName?: string;
  // Role/user-level differentiation fields for dashboard analytics and audits
  submittedByUserId?: string;
  submittedByRole?: 'staff' | 'hod' | 'admin' | 'public';
  targetRole?: 'staff' | 'hod' | 'admin' | 'public';
  sourceModule?: 'app-rating' | 'landing-feedback' | 'hod-question-review' | 'hod-paper-review' | 'admin-review' | 'other';
  itemType?: 'question' | 'paper' | 'app';
  itemId?: string;
  department?: string;
  institution?: string;
  place?: string;
}

/**
 * Utility type to convert Firestore timestamps to Dates
 */
export type ConvertTimestamps<T> = {
  [K in keyof T]: T[K] extends FirestoreDate
    ? Date
    : T[K] extends FirestoreDate | undefined
    ? Date | undefined
    : T[K] extends object
    ? ConvertTimestamps<T[K]>
    : T[K];
};
