import React, { useState, useEffect } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { 
  Users, 
  Settings, 
  FileText, 
  Shield,
  TrendingUp,
  ArrowRight,
  Activity,
  Database,
  Palette,
  BarChart3,
  Bell,
  Star,
  BookOpen,
  Monitor,
  Building2,
  Image,
  Mail,
  KeyRound
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import DashboardLayout from '@/components/layout/DashboardLayout';
import { useAuth } from '@/contexts/AuthContext';
import { useQuestionStore } from '@/stores/questionStore';
import { useQuestionPaperStore } from '@/stores/questionPaperStore';
import { useFeedbackStore } from '@/stores/feedbackStore';
import AdminAnalytics from '@/components/admin/AdminAnalytics';
import RoleManagement from '@/components/admin/RoleManagement';
import AppSettings from '@/components/admin/AppSettings';
import ExamTypeManagement from '@/components/admin/ExamTypeManagement';
import AdminNotifications from '@/components/admin/AdminNotifications';
import UserActivityMonitor from '@/components/admin/UserActivityMonitor';
import DepartmentManagement from '@/components/admin/DepartmentManagement';
import AppLogoSettings from '@/components/admin/AppLogoSettings';
import AnalyticsWidget from '@/components/admin/AnalyticsWidget';
import EmailNotificationSettings from '@/components/settings/EmailNotificationSettings';
import FeedbackWidget from '@/components/common/FeedbackWidget';
import AdminUnlockOversight from '@/components/admin/AdminUnlockOversight';
import AdminSubmittedPapers from '@/components/admin/AdminSubmittedPapers';
import { firestoreDepartmentService, firestoreUserService } from '@/services/firebase/firestore-database';

const AdminDashboard: React.FC = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [searchParams, setSearchParams] = useSearchParams();
  const tabFromUrl = searchParams.get('tab') || 'overview';
  const [activeTab, setActiveTab] = useState(tabFromUrl);
  const [departmentsCount, setDepartmentsCount] = useState<number>(0);
  const [derivedDepartmentsCount, setDerivedDepartmentsCount] = useState<number>(0);
  const [managedUsersCount, setManagedUsersCount] = useState<number>(0);
  const { questions, notifications } = useQuestionStore();
  const { papers } = useQuestionPaperStore();
  const { feedbacks } = useFeedbackStore();

  useEffect(() => {
    const unsubDepartments = firestoreDepartmentService.onDepartmentsChange((list) => {
      setDepartmentsCount(list.length);
    });
    const unsubUsers = firestoreUserService.onUsersChange((list) => {
      setManagedUsersCount(list.length);
      // Fallback source: derive departments from user profiles when
      // departments collection is empty or inaccessible.
      const unique = new Set(
        list
          .map((u) => (u.department || '').trim())
          .filter((d) => d.length > 0)
      );
      setDerivedDepartmentsCount(unique.size);
    });
    return () => {
      try { unsubDepartments(); } catch {}
      try { unsubUsers(); } catch {}
    };
  }, []);

  // Sync tab with URL
  useEffect(() => {
    const tab = searchParams.get('tab');
    if (tab && tab !== activeTab) {
      setActiveTab(tab);
    }
  }, [searchParams]);

  const handleTabChange = (tab: string) => {
    setActiveTab(tab);
    setSearchParams({ tab });
  };

  const allNotifications = notifications;
  const unreadCount = allNotifications.filter(n => !n.isRead).length;

  const stats = [
    { 
      icon: Users, 
      label: 'Total Users', 
      value: managedUsersCount.toString(), 
      change: 'Managed accounts',
      gradient: 'from-blue-500 to-cyan-500',
      bgGradient: 'from-blue-500/10 to-cyan-500/10'
    },
    { 
      icon: Building2, 
      label: 'Departments', 
      value: (departmentsCount > 0 ? departmentsCount : derivedDepartmentsCount).toString(), 
      change: 'Active departments',
      gradient: 'from-green-500 to-emerald-500',
      bgGradient: 'from-green-500/10 to-emerald-500/10'
    },
    { 
      icon: FileText, 
      label: 'Total Questions', 
      value: questions.length.toString(), 
      change: 'Generated by staff',
      gradient: 'from-purple-500 to-pink-500',
      bgGradient: 'from-purple-500/10 to-pink-500/10'
    },
    { 
      icon: Activity, 
      label: 'Question Papers', 
      value: papers.length.toString(), 
      change: 'Created by staff',
      gradient: 'from-orange-500 to-amber-500',
      bgGradient: 'from-orange-500/10 to-amber-500/10'
    },
  ];

  const quickActions = [
    { icon: Users, label: 'User Management', tab: 'activity', description: 'Monitor user activity', gradient: 'from-blue-500 to-cyan-500' },
    { icon: Shield, label: 'Role Manager', tab: 'roles', description: 'Manage user roles', gradient: 'from-purple-500 to-pink-500' },
    { icon: KeyRound, label: 'Security Oversight', tab: 'security', description: 'Monitor unlock requests', gradient: 'from-amber-500 to-red-500' },
    { icon: Building2, label: 'Departments', tab: 'departments', description: 'Manage departments', gradient: 'from-green-500 to-emerald-500' },
    { icon: BookOpen, label: 'Exam Types', tab: 'exams', description: 'Manage exam types', gradient: 'from-amber-500 to-orange-500' },
    { icon: Settings, label: 'App Settings', tab: 'settings', description: 'Customize app content', gradient: 'from-rose-500 to-pink-500' },
    { icon: Image, label: 'App Logo', tab: 'logo', description: 'Customize app logo', gradient: 'from-indigo-500 to-violet-500' },
    { icon: BarChart3, label: 'Analytics', tab: 'analytics', description: 'View platform analytics', gradient: 'from-teal-500 to-cyan-500' },
    { icon: Bell, label: 'Alerts', tab: 'alerts', description: 'Manage notifications', gradient: 'from-red-500 to-rose-500' },
    { icon: Mail, label: 'Email Settings', tab: 'email', description: 'Configure email alerts', gradient: 'from-sky-500 to-blue-500' },
    { icon: FileText, label: 'Submitted Papers', tab: 'papers', description: 'View submitted papers', gradient: 'from-violet-500 to-purple-500' },
  ];

  return (
    <DashboardLayout>
      <div className="space-y-8">
        {/* Welcome Section */}
        <div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-orange-500 via-amber-500 to-yellow-500 p-8 text-white">
          <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.1)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.1)_1px,transparent_1px)] bg-[size:32px_32px]" />
          <div className="relative">
            <h1 className="text-3xl font-bold mb-2">Admin Dashboard 🛡️</h1>
            <p className="text-white/80 mb-6">Full control over QGenesis platform</p>
            <div className="flex flex-wrap gap-4">
              <Button 
                variant="secondary" 
                className="bg-white/20 hover:bg-white/30 text-white border-0 backdrop-blur-sm"
                onClick={() => handleTabChange('roles')}
              >
                <Users className="w-4 h-4 mr-2" />
                Manage Users
              </Button>
              <Button 
                variant="secondary" 
                className="bg-white/20 hover:bg-white/30 text-white border-0 backdrop-blur-sm"
                onClick={() => handleTabChange('analytics')}
              >
                <BarChart3 className="w-4 h-4 mr-2" />
                View Analytics
              </Button>
            </div>
          </div>
        </div>

        {/* Tabs */}
        <Tabs value={activeTab} onValueChange={handleTabChange}>
          <TabsList className="flex w-full justify-start overflow-x-auto snap-x lg:flex-wrap lg:w-auto">
            <TabsTrigger value="overview" className="flex items-center gap-2">
              <Activity className="h-4 w-4" />
              <span className="hidden sm:inline">Overview</span>
            </TabsTrigger>
            <TabsTrigger value="activity" className="flex items-center gap-2">
              <Monitor className="h-4 w-4" />
              <span className="hidden sm:inline">Users</span>
            </TabsTrigger>
            <TabsTrigger value="roles" className="flex items-center gap-2">
              <Shield className="h-4 w-4" />
              <span className="hidden sm:inline">Roles</span>
            </TabsTrigger>
            <TabsTrigger value="security" className="flex items-center gap-2">
              <KeyRound className="h-4 w-4" />
              <span className="hidden sm:inline">Security</span>
            </TabsTrigger>
            <TabsTrigger value="departments" className="flex items-center gap-2">
              <Building2 className="h-4 w-4" />
              <span className="hidden sm:inline">Depts</span>
            </TabsTrigger>
            <TabsTrigger value="exams" className="flex items-center gap-2">
              <BookOpen className="h-4 w-4" />
              <span className="hidden sm:inline">Exams</span>
            </TabsTrigger>
            <TabsTrigger value="settings" className="flex items-center gap-2">
              <Settings className="h-4 w-4" />
              <span className="hidden sm:inline">Settings</span>
            </TabsTrigger>
            <TabsTrigger value="logo" className="flex items-center gap-2">
              <Image className="h-4 w-4" />
              <span className="hidden sm:inline">Logo</span>
            </TabsTrigger>
            <TabsTrigger value="analytics" className="flex items-center gap-2">
              <BarChart3 className="h-4 w-4" />
              <span className="hidden sm:inline">Analytics</span>
            </TabsTrigger>
            <TabsTrigger value="alerts" className="flex items-center gap-2 relative">
              <Bell className="h-4 w-4" />
              <span className="hidden sm:inline">Alerts</span>
              {unreadCount > 0 && (
                <Badge className="absolute -top-1 -right-1 h-5 w-5 p-0 flex items-center justify-center text-xs bg-destructive">
                  {unreadCount > 99 ? '99+' : unreadCount}
                </Badge>
              )}
            </TabsTrigger>
            <TabsTrigger value="email" className="flex items-center gap-2">
              <Mail className="h-4 w-4" />
              <span className="hidden sm:inline">Email</span>
            </TabsTrigger>
            <TabsTrigger value="papers" className="flex items-center gap-2">
              <FileText className="h-4 w-4" />
              <span className="hidden sm:inline">Papers</span>
            </TabsTrigger>
          </TabsList>

          <TabsContent value="overview" className="mt-6 space-y-6">
            {/* Analytics Widget */}
            <AnalyticsWidget />
            
            {/* Stats Grid */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
              {stats.map((stat, index) => (
                <Card key={index} className="relative overflow-hidden border-border/50 hover:shadow-lg transition-all duration-300 hover:scale-[1.02]">
                  <div className={`absolute inset-0 bg-gradient-to-br ${stat.bgGradient} opacity-50`} />
                  <CardContent className="relative p-6">
                    <div className="flex items-start justify-between">
                      <div>
                        <p className="text-sm text-muted-foreground mb-1">{stat.label}</p>
                        <p className="text-3xl font-bold text-foreground">{stat.value}</p>
                        <p className="text-xs text-muted-foreground mt-2 flex items-center gap-1">
                          <TrendingUp className="w-3 h-3" />
                          {stat.change}
                        </p>
                      </div>
                      <div className={`w-12 h-12 rounded-xl bg-gradient-to-br ${stat.gradient} flex items-center justify-center shadow-lg`}>
                        <stat.icon className="w-6 h-6 text-white" />
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>

            {/* Quick Actions */}
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
              {quickActions.map((action, index) => (
                <Card 
                  key={index} 
                  className="h-full border-border/50 hover:shadow-lg transition-all duration-300 hover:scale-[1.02] cursor-pointer group"
                  onClick={() => handleTabChange(action.tab)}
                >
                  <CardContent className="p-6">
                    <div className={`w-12 h-12 rounded-xl bg-gradient-to-br ${action.gradient} flex items-center justify-center shadow-lg mb-4 group-hover:scale-110 transition-transform`}>
                      <action.icon className="w-6 h-6 text-white" />
                    </div>
                    <h3 className="font-semibold text-foreground mb-1">{action.label}</h3>
                    <p className="text-sm text-muted-foreground">{action.description}</p>
                  </CardContent>
                </Card>
              ))}
            </div>

            {/* Recent Feedbacks */}
            <Card className="border-border/50">
              <CardHeader className="flex flex-row items-center justify-between">
                <CardTitle className="text-lg font-semibold">Recent Feedbacks</CardTitle>
                <Button variant="ghost" size="sm" className="gap-1" onClick={() => handleTabChange('analytics')}>
                  View All <ArrowRight className="w-4 h-4" />
                </Button>
              </CardHeader>
              <CardContent className="space-y-4">
                {feedbacks.length === 0 ? (
                  <p className="text-center text-muted-foreground py-4">No feedbacks yet</p>
                ) : (
                  feedbacks.slice(0, 4).map((feedback, index) => (
                    <div key={index} className="flex items-center gap-4 p-3 rounded-xl bg-muted/30 hover:bg-muted/50 transition-colors">
                      <div className="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-purple-600 flex items-center justify-center text-white font-medium">
                        {feedback.userName?.charAt(0) || 'U'}
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium text-foreground truncate">{feedback.comment}</p>
                        <div className="flex items-center gap-2 mt-1">
                          <Badge variant="outline" className="text-xs">{feedback.userType}</Badge>
                          <div className="flex items-center">
                            {[1, 2, 3, 4, 5].map((star) => (
                              <Star
                                key={star}
                                className={`w-3 h-3 ${star <= feedback.rating ? 'text-yellow-500 fill-yellow-500' : 'text-muted'}`}
                              />
                            ))}
                          </div>
                        </div>
                      </div>
                    </div>
                  ))
                )}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="analytics" className="mt-6">
            <AdminAnalytics />
          </TabsContent>

          <TabsContent value="roles" className="mt-6">
            <RoleManagement />
          </TabsContent>

          <TabsContent value="departments" className="mt-6">
            <DepartmentManagement />
          </TabsContent>

          <TabsContent value="exams" className="mt-6">
            <ExamTypeManagement />
          </TabsContent>

          <TabsContent value="settings" className="mt-6">
            <AppSettings />
          </TabsContent>

          <TabsContent value="logo" className="mt-6">
            <AppLogoSettings />
          </TabsContent>

          <TabsContent value="analytics" className="mt-6">
            <AdminAnalytics />
          </TabsContent>

          <TabsContent value="alerts" className="mt-6">
            <AdminNotifications />
          </TabsContent>

          <TabsContent value="activity" className="mt-6">
            <UserActivityMonitor />
          </TabsContent>

          <TabsContent value="email" className="mt-6">
            <EmailNotificationSettings />
          </TabsContent>

          <TabsContent value="security" className="mt-6">
            <AdminUnlockOversight />
          </TabsContent>

          <TabsContent value="papers" className="mt-6">
            <AdminSubmittedPapers />
          </TabsContent>
        </Tabs>

        {/* Feedback Widget */}
        <FeedbackWidget userType="admin" />
      </div>
    </DashboardLayout>
  );
};

export default AdminDashboard;